// <auto-generated />
using System;
using System.Text.Json;
using IdleTerraria.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdleTerraria.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261006112110_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdleTerraria.Api.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.Biome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaximumLevel")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_level");

                    b.Property<int>("MinimumLevel")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("biomes", t =>
                        {
                            t.HasCheckConstraint("CK_biomes_maximum_level_valid", "\"maximum_level\" IS NULL OR \"maximum_level\" >= \"minimum_level\"");

                            t.HasCheckConstraint("CK_biomes_minimum_level_non_negative", "\"minimum_level\" >= 0");
                        });
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.BiomeMob", b =>
                {
                    b.Property<int>("BiomeId")
                        .HasColumnType("integer")
                        .HasColumnName("biome_id");

                    b.Property<int>("MobTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("mob_template_id");

                    b.Property<int>("SpawnWeight")
                        .HasColumnType("integer")
                        .HasColumnName("spawn_weight");

                    b.HasKey("BiomeId", "MobTemplateId");

                    b.HasIndex("MobTemplateId");

                    b.ToTable("biome_mobs", t =>
                        {
                            t.HasCheckConstraint("CK_biome_mobs_spawn_weight_positive", "\"spawn_weight\" > 0");
                        });
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.HeadquarterNpc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unlocked");

                    b.Property<int>("MoralePercentage")
                        .HasColumnType("integer")
                        .HasColumnName("morale_percentage");

                    b.Property<string>("NpcName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("npc_name");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("headquarter_npcs");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Prefix")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Normal")
                        .HasColumnName("prefix");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.Property<int>("UpgradeLevel")
                        .HasColumnType("integer")
                        .HasColumnName("upgrade_level");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TemplateId");

                    b.ToTable("inventory", t =>
                        {
                            t.HasCheckConstraint("CK_inventory_quantity_positive", "\"quantity\" > 0");

                            t.HasCheckConstraint("CK_inventory_upgrade_level_range", "\"upgrade_level\" >= 0 AND \"upgrade_level\" <= 10");
                        });
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.ItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("Equipable")
                        .HasColumnType("boolean")
                        .HasColumnName("equipable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("item_categories");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.ItemCombatProfile", b =>
                {
                    b.Property<int>("ItemTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("item_template_id");

                    b.Property<int>("ArmorPenetration")
                        .HasColumnType("integer")
                        .HasColumnName("armor_penetration");

                    b.Property<decimal>("AttackIntervalSeconds")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("attack_interval_seconds");

                    b.Property<int>("BaseDamage")
                        .HasColumnType("integer")
                        .HasColumnName("base_damage");

                    b.Property<decimal>("CriticalChance")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("critical_chance");

                    b.HasKey("ItemTemplateId");

                    b.ToTable("item_combat_profiles", t =>
                        {
                            t.HasCheckConstraint("CK_item_combat_profiles_armor_penetration_non_negative", "\"armor_penetration\" >= 0");

                            t.HasCheckConstraint("CK_item_combat_profiles_attack_interval_positive", "\"attack_interval_seconds\" > 0");

                            t.HasCheckConstraint("CK_item_combat_profiles_base_damage_non_negative", "\"base_damage\" >= 0");

                            t.HasCheckConstraint("CK_item_combat_profiles_critical_chance_range", "\"critical_chance\" >= 0 AND \"critical_chance\" <= 1");
                        });
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.ItemTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("BaseValue")
                        .HasColumnType("bigint")
                        .HasColumnName("base_value");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsTradable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tradable");

                    b.Property<int>("MaxStackSize")
                        .HasColumnType("integer")
                        .HasColumnName("max_stack_size");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CategoryId", "Tier");

                    b.ToTable("item_templates", t =>
                        {
                            t.HasCheckConstraint("CK_item_templates_base_value_non_negative", "\"base_value\" >= 0");

                            t.HasCheckConstraint("CK_item_templates_max_stack_size_positive", "\"max_stack_size\" > 0");

                            t.HasCheckConstraint("CK_item_templates_tier_range", "\"tier\" >= 1 AND \"tier\" <= 12");
                        });
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.Loadout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArmorInvId")
                        .HasColumnType("uuid")
                        .HasColumnName("armor_inv_id");

                    b.Property<Guid?>("PetInvId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_inv_id");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("role_type");

                    b.Property<Guid?>("WeaponInvId")
                        .HasColumnType("uuid")
                        .HasColumnName("weapon_inv_id");

                    b.HasKey("Id");

                    b.HasIndex("ArmorInvId");

                    b.HasIndex("PetInvId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("WeaponInvId");

                    b.ToTable("loadouts");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.MobLootDrop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DropChance")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("drop_chance");

                    b.Property<int>("ItemTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("item_template_id");

                    b.Property<int>("MaximumQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_quantity");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_quantity");

                    b.Property<int>("MobTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("mob_template_id");

                    b.HasKey("Id");

                    b.HasIndex("ItemTemplateId");

                    b.HasIndex("MobTemplateId", "ItemTemplateId")
                        .IsUnique();

                    b.ToTable("mob_loot_drops", t =>
                        {
                            t.HasCheckConstraint("CK_mob_loot_drops_drop_chance_range", "\"drop_chance\" >= 0 AND \"drop_chance\" <= 1");

                            t.HasCheckConstraint("CK_mob_loot_drops_quantity_range", "\"minimum_quantity\" > 0 AND \"maximum_quantity\" >= \"minimum_quantity\"");
                        });
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.MobTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseExperience")
                        .HasColumnType("integer")
                        .HasColumnName("base_experience");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<long>("MaximumGold")
                        .HasColumnType("bigint")
                        .HasColumnName("maximum_gold");

                    b.Property<long>("MinimumGold")
                        .HasColumnType("bigint")
                        .HasColumnName("minimum_gold");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("mob_templates", t =>
                        {
                            t.HasCheckConstraint("CK_mob_templates_base_experience_non_negative", "\"base_experience\" >= 0");

                            t.HasCheckConstraint("CK_mob_templates_gold_range_valid", "\"minimum_gold\" >= 0 AND \"maximum_gold\" >= \"minimum_gold\"");

                            t.HasCheckConstraint("CK_mob_templates_level_positive", "\"level\" > 0");
                        });
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("ArenaElo")
                        .HasColumnType("integer")
                        .HasColumnName("arena_elo");

                    b.Property<int?>("CurrentBiomeId")
                        .HasColumnType("integer")
                        .HasColumnName("current_biome_id");

                    b.Property<int>("Energy")
                        .HasColumnType("integer")
                        .HasColumnName("energy");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint")
                        .HasColumnName("experience");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint")
                        .HasColumnName("gold");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("SkillPoints")
                        .HasColumnType("integer")
                        .HasColumnName("skill_points");

                    b.Property<int>("Stardust")
                        .HasColumnType("integer")
                        .HasColumnName("stardust");

                    b.Property<int>("StatsBoughtN")
                        .HasColumnType("integer")
                        .HasColumnName("stats_bought_n");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("players");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.PlayerActivityState", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("activity_type");

                    b.Property<int?>("BiomeId")
                        .HasColumnType("integer")
                        .HasColumnName("biome_id");

                    b.Property<DateTime>("LastBatchCalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_batch_calculated_at");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("PlayerId");

                    b.ToTable("player_activity_states");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.PlayerProfession", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("ProfessionType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("profession_type");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint")
                        .HasColumnName("experience");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.HasKey("PlayerId", "ProfessionType");

                    b.ToTable("player_professions");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.PlayerStats", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("StatDexterity")
                        .HasColumnType("integer")
                        .HasColumnName("stat_dexterity");

                    b.Property<int>("StatLuck")
                        .HasColumnType("integer")
                        .HasColumnName("stat_luck");

                    b.Property<int>("StatStrength")
                        .HasColumnType("integer")
                        .HasColumnName("stat_strength");

                    b.Property<int>("StatVitality")
                        .HasColumnType("integer")
                        .HasColumnName("stat_vitality");

                    b.HasKey("PlayerId");

                    b.ToTable("player_stats");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.PlayerUnlockedNode", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("NodeId")
                        .HasColumnType("integer")
                        .HasColumnName("node_id");

                    b.Property<Guid>("LoadoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("loadout_id");

                    b.HasKey("PlayerId", "NodeId", "LoadoutId");

                    b.HasIndex("LoadoutId");

                    b.HasIndex("NodeId");

                    b.ToTable("player_unlocked_nodes");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.PvpLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AttackerId")
                        .HasColumnType("uuid")
                        .HasColumnName("attacker_id");

                    b.Property<JsonDocument>("BattleData")
                        .HasColumnType("jsonb")
                        .HasColumnName("battle_data");

                    b.Property<Guid?>("DefenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("defender_id");

                    b.HasKey("Id");

                    b.HasIndex("AttackerId");

                    b.HasIndex("DefenderId");

                    b.ToTable("pvp_logs");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EloRating")
                        .HasColumnType("integer")
                        .HasColumnName("elo_rating");

                    b.Property<int>("GloryEmblems")
                        .HasColumnType("integer")
                        .HasColumnName("glory_emblems");

                    b.Property<long>("GoldVault")
                        .HasColumnType("bigint")
                        .HasColumnName("gold_vault");

                    b.Property<Guid?>("LeaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("leader_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.ToTable("settlements");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.SettlementMember", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<long>("ContributionGold")
                        .HasColumnType("bigint")
                        .HasColumnName("contribution_gold");

                    b.Property<bool>("IsRegisteredForWar")
                        .HasColumnType("boolean")
                        .HasColumnName("is_registered_for_war");

                    b.Property<Guid?>("SettlementId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_id");

                    b.HasKey("PlayerId");

                    b.HasIndex("SettlementId");

                    b.ToTable("settlement_members");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.SettlementUpgrade", b =>
                {
                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_id");

                    b.Property<string>("UpgradeType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("upgrade_type");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.HasKey("SettlementId", "UpgradeType");

                    b.ToTable("settlement_upgrades");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.SkillTree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ModifierValue")
                        .HasColumnType("numeric")
                        .HasColumnName("modifier_value");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("node_name");

                    b.Property<string>("StatModifier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("stat_modifier");

                    b.Property<string>("TreeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tree_type");

                    b.HasKey("Id");

                    b.ToTable("skill_trees");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.WanderingShopStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("PriceInGold")
                        .HasColumnType("bigint")
                        .HasColumnName("price_in_gold");

                    b.Property<decimal>("PriceModifierPct")
                        .HasColumnType("numeric")
                        .HasColumnName("price_modifier_pct");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("wandering_shop_stock");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.BiomeMob", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.Biome", "Biome")
                        .WithMany("MobPool")
                        .HasForeignKey("BiomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdleTerraria.Api.Entities.MobTemplate", "MobTemplate")
                        .WithMany("Biomes")
                        .HasForeignKey("MobTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biome");

                    b.Navigation("MobTemplate");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.HeadquarterNpc", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.Inventory", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IdleTerraria.Api.Entities.ItemTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Player");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.ItemCombatProfile", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.ItemTemplate", "ItemTemplate")
                        .WithOne("CombatProfile")
                        .HasForeignKey("IdleTerraria.Api.Entities.ItemCombatProfile", "ItemTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemTemplate");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.ItemTemplate", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.ItemCategory", "Category")
                        .WithMany("ItemTemplates")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.Loadout", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.Inventory", "Armor")
                        .WithMany()
                        .HasForeignKey("ArmorInvId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IdleTerraria.Api.Entities.Inventory", "Pet")
                        .WithMany()
                        .HasForeignKey("PetInvId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IdleTerraria.Api.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("IdleTerraria.Api.Entities.Inventory", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponInvId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Armor");

                    b.Navigation("Pet");

                    b.Navigation("Player");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.MobLootDrop", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.ItemTemplate", "ItemTemplate")
                        .WithMany("LootDrops")
                        .HasForeignKey("ItemTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdleTerraria.Api.Entities.MobTemplate", "MobTemplate")
                        .WithMany("LootDrops")
                        .HasForeignKey("MobTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemTemplate");

                    b.Navigation("MobTemplate");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.Player", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.Account", "Account")
                        .WithOne("Player")
                        .HasForeignKey("IdleTerraria.Api.Entities.Player", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.PlayerActivityState", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.PlayerProfession", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.PlayerStats", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.Player", "Player")
                        .WithOne("Stats")
                        .HasForeignKey("IdleTerraria.Api.Entities.PlayerStats", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.PlayerUnlockedNode", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.Loadout", "Loadout")
                        .WithMany()
                        .HasForeignKey("LoadoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdleTerraria.Api.Entities.SkillTree", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdleTerraria.Api.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loadout");

                    b.Navigation("Node");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.PvpLog", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.Player", "Attacker")
                        .WithMany()
                        .HasForeignKey("AttackerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IdleTerraria.Api.Entities.Player", "Defender")
                        .WithMany()
                        .HasForeignKey("DefenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Attacker");

                    b.Navigation("Defender");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.Settlement", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.Player", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId");

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.SettlementMember", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdleTerraria.Api.Entities.Settlement", "Settlement")
                        .WithMany()
                        .HasForeignKey("SettlementId");

                    b.Navigation("Player");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.SettlementUpgrade", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.Settlement", "Settlement")
                        .WithMany()
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.WanderingShopStock", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.ItemTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.Account", b =>
                {
                    b.Navigation("Player");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.Biome", b =>
                {
                    b.Navigation("MobPool");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.ItemCategory", b =>
                {
                    b.Navigation("ItemTemplates");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.ItemTemplate", b =>
                {
                    b.Navigation("CombatProfile");

                    b.Navigation("LootDrops");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.MobTemplate", b =>
                {
                    b.Navigation("Biomes");

                    b.Navigation("LootDrops");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.Player", b =>
                {
                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
