// <auto-generated />
using System;
using IdleTerraria.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdleTerraria.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260920132400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdleTerraria.Api.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ArenaElo")
                        .HasColumnType("integer")
                        .HasColumnName("arena_elo");

                    b.Property<int?>("CurrentBiomeId")
                        .HasColumnType("integer")
                        .HasColumnName("current_biome_id");

                    b.Property<int>("Energy")
                        .HasColumnType("integer")
                        .HasColumnName("energy");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint")
                        .HasColumnName("experience");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint")
                        .HasColumnName("gold");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("Stardust")
                        .HasColumnType("integer")
                        .HasColumnName("stardust");

                    b.Property<int>("StatsBoughtN")
                        .HasColumnType("integer")
                        .HasColumnName("stats_bought_n");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("players");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.PlayerStats", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("StatDexterity")
                        .HasColumnType("integer")
                        .HasColumnName("stat_dexterity");

                    b.Property<int>("StatLuck")
                        .HasColumnType("integer")
                        .HasColumnName("stat_luck");

                    b.Property<int>("StatStrength")
                        .HasColumnType("integer")
                        .HasColumnName("stat_strength");

                    b.HasKey("PlayerId");

                    b.ToTable("player_stats");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.PlayerStats", b =>
                {
                    b.HasOne("IdleTerraria.Api.Entities.Player", "Player")
                        .WithOne("Stats")
                        .HasForeignKey("IdleTerraria.Api.Entities.PlayerStats", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IdleTerraria.Api.Entities.Player", b =>
                {
                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
